---
name: build
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: Ensure gofmt
        run: test -z "$(gofmt -s -d .)"
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff --no-patch --exit-code
      - name: Run linters
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.39.0
          skip-go-installation: true
          args: --timeout=3m0s
      - name: Install go-acc
        run: go install github.com/ory/go-acc@v0.2.6
      - name: Run tests
        run: go-acc --output profile.cov ./... -- -v
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1.4.3
        with:
          path-to-profile: profile.cov
      - name: Build with Goreleaser
        uses: goreleaser/goreleaser-action@v2.4.1
        with:
          version: v0.161.1
          args: release --snapshot --skip-publish --rm-dist
        env:
          PRIVATE_ACCESS_TOKEN: placeholder
